export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    USERS_INFO_REQUEST: 'USERS_INFO_REQUEST',
    USERS_INFO_SUCCESS: 'USERS_INFO_SUCCESS',
    USERS_INFO_FAILURE: 'USERS_INFO_FAILURE',

    OFFICE_INFO_REQUEST: 'OFFICE_INFO_REQUEST',
    OFFICE_INFO_SUCCESS: 'OFFICE_INFO_SUCCESS',
    OFFICE_INFO_FAILURE: 'OFFICE_INFO_FAILURE'
};
